export const GET_ALL_CONTENT_REQUEST = "GET_ALL_CONTENT_REQUEST";
export const GET_ALL_CONTENT_SUCCESS = "GET_ALL_CONTENT_SUCCESS";
export const GET_ALL_CONTENT_FAILURE = "GET_ALL_CONTENT_FAILURE";

export const GET_STUDENT_CONTENT_REQUEST = "GET_STUDENT_CONTENT_REQUEST";
export const GET_STUDENT_CONTENT_SUCCESS = "GET_STUDENT_CONTENT_SUCCESS";
export const GET_STUDENT_CONTENT_FAILURE = "GET_STUDENT_CONTENT_FAILURE";

export const ADD_NEW_CONTENT_REQUEST = "ADD_NEW_CONTENT_REQUEST";
export const ADD_NEW_CONTENT_SUCCESS = "ADD_NEW_CONTENT_SUCCESS";
export const ADD_NEW_CONTENT_FAILURE = "ADD_NEW_CONTENT_FAILURE";

export const UPDATE_CONTENT_REQUEST = "UPDATE_CONTENT_REQUEST";
export const UPDATE_CONTENT_SUCCESS = "UPDATE_CONTENT_SUCCESS";
export const UPDATE_CONTENT_FAILURE = "UPDATE_CONTENT_FAILURE";

export const REMOVE_CONTENT_REQUEST = "REMOVE_CONTENT_REQUEST";
export const REMOVE_CONTENT_SUCCESS = "REMOVE_CONTENT_SUCCESS";
export const REMOVE_CONTENT_FAILURE = "REMOVE_CONTENT_FAILURE";
