export const GET_ALL_COURSES_REQUEST = "GET_ALL_COURSES_REQUEST";
export const GET_ALL_COURSES_SUCCESS = "GET_ALL_COURSES_SUCCESS";
export const GET_ALL_COURSES_FAILURE = "GET_ALL_COURSES_FAILURE";

export const ADD_NEW_COURSE_REQUEST = "ADD_NEW_COURSE_REQUEST";
export const ADD_NEW_COURSE_SUCCESS = "ADD_NEW_COURSE_SUCCESS";
export const ADD_NEW_COURSE_FAILURE = "ADD_NEW_COURSE_FAILURE";

export const UPDATE_COURSE_REQUEST = "UPDATE_COURSE_REQUEST";
export const UPDATE_COURSE_SUCCESS = "UPDATE_COURSE_SUCCESS";
export const UPDATE_COURSE_FAILURE = "UPDATE_COURSE_FAILURE";

export const REMOVE_COURSE_REQUEST = "REMOVE_COURSE_REQUEST";
export const REMOVE_COURSE_SUCCESS = "REMOVE_COURSE_SUCCESS";
export const REMOVE_COURSE_FAILURE = "REMOVE_COURSE_FAILURE";

export const FILTER_CATEGORY = "FILTER_CATEGORY";
export const FILTER_TYPE = "FILTER_TYPE";
