export const GET_MY_COURSES_REQUEST = "GET_MY_COURSES_REQUEST";
export const GET_MY_COURSES_SUCCESS = "GET_MY_COURSES_SUCCESS";
export const GET_MY_COURSES_FAILURE = "GET_MY_COURSES_FAILURE";

export const ADD_MY_COURSE_REQUEST = "ADD_MY_COURSE_REQUEST";
export const ADD_MY_COURSE_SUCCESS = "ADD_MY_COURSE_SUCCESS";
export const ADD_MY_COURSE_FAILURE = "ADD_MY_COURSE_FAILURE";

export const REMOVE_MY_COURSE_REQUEST = "REMOVE_MY_COURSE_REQUEST";
export const REMOVE_MY_COURSE_SUCCESS = "REMOVE_MY_COURSE_SUCCESS";
export const REMOVE_MY_COURSE_FAILURE = "REMOVE_MY_COURSE_FAILURE";
