export const GET_ALL_STUDENTS_REQUEST = "GET_ALL_STUDENTS_REQUEST";
export const GET_ALL_STUDENTS_SUCCESS = "GET_ALL_STUDENTS_SUCCESS";
export const GET_ALL_STUDENTS_FAILURE = "GET_ALL_STUDENTS_FAILURE";

export const UPDATE_STUDENT_ROLE_REQUEST = "UPDATE_STUDENT_ROLE_REQUEST";
export const UPDATE_STUDENT_ROLE_SUCCESS = "UPDATE_STUDENT_ROLE_SUCCESS";
export const UPDATE_STUDENT_ROLE_FAILURE = "UPDATE_STUDENT_ROLE_FAILURE";

export const UPDATE_STUDENT_COURSES_REQUEST = "UPDATE_STUDENT_COURSES_REQUEST";
export const UPDATE_STUDENT_COURSES_SUCCESS = "UPDATE_STUDENT_COURSES_SUCCESS";
export const UPDATE_STUDENT_COURSES_FAILURE = "UPDATE_STUDENT_COURSES_FAILURE";
